version: '3.8'

services:
  voting-bot:
    build: .
    environment:
      - TARANTOOL_HOST=tarantool
      - MATTERMOST_BOT_TOKEN=your_bot_token
      - MATTERMOST_URL=http://mattermost:8065
    depends_on:
      - tarantool
      - mattermost

  tarantool:
    image: tarantool/tarantool:2.10
    ports:
      - "3301:3301"
    volumes:
      - ./tarantool:/opt/tarantool
    command: tarantool /opt/tarantool/init.lua

  mattermost:
    image: mattermost/mattermost-team-edition:7.8
    ports:
      - "8065:8065"
    environment:
      - MM_SERVICESETTINGS_SITEURL=http://mattermost:8065